apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-hello-deployment
  namespace: python-hello
  labels:
    app: python-hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-hello
  template:
    metadata:
      labels:
        app: python-hello
    spec:
      containers:
        - name: python-hello
          image: didietap/python-hello:latest
          ports:
            - containerPort: 80
