apiVersion: v1
kind: Service
metadata:
  name: python-hello-service
spec:
  selector:
    app: python-hello
  ports:
    - protocol: TCP
      port: 80        # Exposed service port
      targetPort: 80  # Container port in the pod
  type: NodePort
